# Generated by Django 5.0.1 on 2024-01-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_rename_subnode_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
