# Generated by Django 5.0.1 on 2024-01-18 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_node_is_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='sub_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.node'),
        ),
    ]
